apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app-container
        image: pingu150/streamlit-app
        ports:
        - containerPort: 8501
        envFrom:
        - secretRef:
            name: streamlit-env
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  type: NodePort
  selector:
    app: streamlit-app
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30001
