name: Test Environment Variables

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  test-env-vars:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print environment variables
      - name: Print Environment Variables
        env:
          DATA_URL: ${{ vars.DATA_URL }}
          IMAGE_URL: ${{ vars.IMAGE_URL }}
          CHART_URL: ${{ vars.CHART_URL }}
        run: |
          echo "DATA_URL: $DATA_URL"
          echo "IMAGE_URL: $IMAGE_URL"
          echo "CHART_URL: $CHART_URL"

      # Step 3: Verify environment variables are set
      - name: Verify Variables
        env:
          DATA_URL: ${{ vars.DATA_URL }}
          IMAGE_URL: ${{ vars.IMAGE_URL }}
          CHART_URL: ${{ vars.CHART_URL }}
        run: |
          if [ -z "$DATA_URL" ]; then
            echo "DATA_URL is not set!" && exit 1
          fi
          if [ -z "$IMAGE_URL" ]; then
            echo "IMAGE_URL is not set!" && exit 1
          fi
          if [ -z "$CHART_URL" ]; then
            echo "CHART_URL is not set!" && exit 1
          fi
          echo "All environment variables are set!"
