name: Deploy Streamlit App

on:
  push:
    branches:
      - prod  # Run workflow on pushes to the prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build and run Docker container
      - name: Build and run Docker container
        env:
          DATA_URL: ${{ secrets.DATA_URL }}
          IMAGE_URL: ${{ secrets.IMAGE_URL }}
          CHART_URL: ${{ secrets.CHART_URL }}
        run: |
          docker build -t streamlit-app .
          docker run -e DATA_URL=$DATA_URL -e IMAGE_URL=$IMAGE_URL -e CHART_URL=$CHART_URL -p 8501:8501 streamlit-app
