name: Deploy Streamlit App

on:
  push:
    branches:
      - prod  # Trigger deployment on pushes to the prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t streamlit-app .

      # Step 3: Save Docker image as tarball
      - name: Save Docker image
        run: |
          docker save -o streamlit-app.tar streamlit-app

      # Step 4: Copy Docker tarball to the VPS server
      - name: Copy Docker tarball to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: streamlit-app.tar
          target: /home/${{ secrets.SERVER_USERNAME }}/streamlit-app.tar

      # Step 5: Deploy Docker container on the VPS server
      - name: Deploy Docker container
        uses: appleboy/ssh-action@v0.1.8  # Correct version
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load < /home/${{ secrets.SERVER_USERNAME }}/streamlit-app.tar
            docker stop streamlit-app || true
            docker rm streamlit-app || true
            docker run -d \
              -e DATA_URL=${{ secrets.DATA_URL }} \
              -e IMAGE_URL=${{ secrets.IMAGE_URL }} \
              -e CHART_URL=${{ secrets.CHART_URL }} \
              -p 8501:8501 \
              --name streamlit-app streamlit-app
